### ISSUE TITLE
Tomocupy tests 

### ISSUE THREAD

**Issue by Mustafa-zubi** [SESAME-Synchrotron/BEATS_recon#5]
getting this error when running the tests provided by tomocupy: 

```
2023-05-03 00:26:25,133 - Processing slice 10
Traceback (most recent call last):
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/bin/tomocupy", line 8, in <module>
    sys.exit(main())
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/bin/tomocupy_cli.py", line 171, in main
    args._func(args)
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/bin/tomocupy_cli.py", line 94, in run_recstep
    clpthandle.recon_steps_all()
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/lib/python3.9/site-packages/tomocupy/rec_steps.py", line 143, in recon_steps_all
    self.recon_try_sino_proj_parallel(data)
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/lib/python3.9/site-packages/tomocupy/rec_steps.py", line 471, in recon_try_sino_proj_parallel
    self.cl_tomo_func.cl_rec.backprojection_try(
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/lib/python3.9/site-packages/tomocupy/linerec.py", line 75, in backprojection_try
    phi = cp.float(cp.pi/2+(lamino_angle)/180*cp.pi)
  File "/PETRA/cluster_software/install/anaconda/envs/tomocupy/lib/python3.9/site-packages/cupy/__init__.py", line 921, in __getattr__
    raise AttributeError(f"module 'cupy' has no attribute {name!r}")
AttributeError: module 'cupy' has no attribute 'float'
F
======================================================================
FAIL: test_full_recon (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/PETRA/cluster_software/source/tomocupy/tests/test_steps_try.py", line 31, in test_full_recon
    self.assertEqual(st, 0)
AssertionError: 256 != 0

----------------------------------------------------------------------
Ran 1 test in 6.782s

FAILED (failures=1)
(tomocupy) [root@gpunode2 tests]#
```

**Comment by gianthk** [comment]
- [ ] install on Rocky BEATS-BL-WS01
- [ ] reproduce error above
